### ISSUE TITLE
Updating mods Crash

### ISSUE THREAD

**Issue by Dorky106** [Artentus/ModMyFactory2#39]
Clicking update mods seems to close the whole program right now.  Not sure what is going on.

**Comment by Artentus** [comment]
Not sure why you are experiencing this, I cannot reproduce it at all. Does your log show anything?

**Comment by Dorky106** [comment]
Which is located where?

**Comment by Artentus** [comment]
%appdata%\ModMyFactoryGUI\logs an Windows and
home/.modmyfactorygui/logs on Linux

**Comment by Dorky106** [comment]
https://pastebin.com/JNe1QMtY

**Comment by Dorky106** [comment]
If it's only checking for checked off mods then
AAI Industry
AAI Signal Transmission
Alien Biomes
Bio Industries
Standard Library
Informatron
Jetpack
Krastorio 2
Robot Attrition
Space Exploration (Experimental)
Space Exploration Graphics (Required)
Space Exploration Postprocess (Required)
Squeak Through

**Comment by Dorky106** [comment]
So when I click to even download space exploration, from the download mods section it also just crashes
https://pastebin.com/YsVxHLjq

**Comment by Artentus** [comment]
I can download all of the latest versions of these mods just fine, but I saw some of them are quite outdated. Which Factorio version are you running?

**Comment by Dorky106** [comment]
1.1.32

**Comment by Artentus** [comment]
Found your problem. Turns out I cannot find anything because this issue no longer exists, I fixed it a while ago.  
But for some reason you have outdated application modules in your installation, not sure how that happened.  
Clean-installing MMF should resolve this completely.

**Comment by Dorky106** [comment]
Odd, as I DL'd a fresh copy, new folder and everything

**Comment by Dorky106** [comment]
Deleted, the mod manager folder, and the appdata folder and yup still crashing. when checking space exploration.
You sure you pushed out the fix?

**Comment by Artentus** [comment]
I just released a new version, please try it.

**Comment by Dorky106** [comment]
Yea, the update seems to have fixed it the issue.

**Comment by Dorky106** [comment]
So the issue semi-still exists.  It happens with the Space Exploration Graphics 1-5

**Comment by Artentus** [comment]
I don't really know what to make of this.  
I can log in through MMF just fine. Updating mods also works just fine.  

Try removing your credentials entirely by keeping both fields empty and saving, then reload MMF and reenter them.  
Maybe something got messed up in the settings.

**Comment by VertexComplex** [comment]
Good news, I seem to have "fixed" it on my end. My copy of Factorio was bought through Steam, and for some reason my factorio.com account wasn't linked to my steam account, so on some pages the site told me I didn't have full access.

I linked the accounts, and to be sure, I also deleted the ModMyFactoryGUI folder under %USERPROFILE%\AppData\Roaming, then restarted MMF.

MMF is now able to log in and download/update mods. I have no idea how this worked before, and then stopped working...
